#!/bin/zsh
# clip2goog - google for selected text

selurl() {
  setopt localoptions extendedglob
  sel=$(xclip -out)
  input=( ${(s::)sel} )
  print ${(j::)input/(#b)([^A-Za-z0-9_.!~*\'\(\)-])/%$(([##16]#match))}
}

firefox "http://google.com/search?q=$(selurl)"
