#!/usr/bin/ruby -s
# goog - google command-line interface
# goog [-q] [num] <string>
# 26aug2008 chneukirchen / revised 06aug2010 / public domain
require 'open-uri'
n = ARGV[0] =~ /^\d+$/ ? ARGV.shift : 5
q = ARGV.join(" ").gsub(/./m) { "%%%02X" % $&.unpack("C").first }
open("http://www.google.com/search?ie=utf-8&oe=utf-8&q=#{q}&num=#{n}").read.
scan(%r{<h3 class="?r"?><a href="([^"]*?)" class=l>(.*?)</a>}) { |url, desc|
  puts url
  puts "  " + desc[0..70].gsub(%r{</?em>}, '')  unless $q
}
