#!/bin/sh
# swaptop - show most swap-using processes
# 17sep2011  +chris+

for f in /proc/[0-9]*; do
  # awk will fail on permission denied
  awk 'BEGIN { swap=0 }
       $30 { pid = $1; name = substr($2,2,length($2)-2) }
       $1=="Swap:" {swap += $2}
       END { if (swap>0) printf "%8d  %s %d\n", swap, name, pid }' \
      $f/stat $f/smaps 2>/dev/null
done | sort -nr 
