#!/bin/sh
# swaptop - show most swap-using processes
# 17sep2011  +chris+

awk '/^Name:/ { name = $2 }
     /^Pid:/ { pid = $2}
     /^VmSwap:/ {
         swap = $2
         if (swap>0)
             printf "%8d  %s %d\n", swap, name, pid
     }' /proc/[0-9]*/status | sort -nr 
